mysql -uroot -proot forliu <d:\Desktop\db\bbs_food.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_foodwith.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_anime.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_animewith.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_political.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_politicalwith.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_forcomplain.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_forcomplainwith.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_historystory.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_historystorywith.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_military.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_militarywith.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_travel.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_travelwith.sql
mysql -uroot -proot forliu <d:\Desktop\db\bbs_user.sql
